from .pfithic import read_countsFile
from .pfithic import read_fragsFile
from .pfithic import read_biasFile
from .pfithic import get_maindic
from .pfithic import make_bins
from .pfithic import make_fragpairs
from .pfithic import calculateProbabilities
from .pfithic import fit_Spline
from .pfithic import calculateSignificant
from .pfithic import plot_splines
from .pfithic import plot_qvalues
from .pfithic import compare_Spline_FDR
from .pfithic import compareFits_Spline